#!/bin/sh

#initial setup for loaners
#OCADU 2015

#removing any parental controls/unnecessary control policies from guest account
dscl . -mcxdelete Users/Guest
rm -f /Library/Managed\ Preferences/Guest/com.apple.familycontrols.contentfilter.plist


#Set time zone
/usr/sbin/systemsetup -settimezone America/Toronto
/usr/sbin/systemsetup -setusingnetworktime on
/usr/sbin/systemsetup -gettime
/usr/sbin/systemsetup -gettimezone


#Let it catch up
sleep 5


# make FireWire networking inactive
/usr/sbin/networksetup -setnetworkserviceenabled FireWire off


#Disable "Remember this network" for Airport
/usr/libexec/airportd prefs RememberRecentNetworks=NO


#remove annoying Adobe Creative Cloud app launch on startup
rm -f /Library/LaunchAgents/com.adobe.AdobeCreativeCloud.plist


#make a symbolic link from /System/Library/CoreServices/Applications/Directory Utility.app 
#to /Applications/Utilities so that Directory Utility.app is easier to access.

if [[ ! -e "/Applications/Utilities/Directory Utility.app" ]]; then
   ln -s "/System/Library/CoreServices/Applications/Directory Utility.app" "/Applications/Utilities/Directory Utility.app"
fi

if [[ -L "/Applications/Utilities/Directory Utility.app" ]]; then
   rm "/Applications/Utilities/Directory Utility.app"
   ln -s "/System/Library/CoreServices/Applications/Directory Utility.app" "/Applications/Utilities/Directory Utility.app"
fi


#make a symbolic link from /System/Library/CoreServices/Applications/Network Utility.app 
#to /Applications/Utilities so that Network Utility.app is easier to access.

if [[ ! -e "/Applications/Utilities/Network Utility.app" ]]; then
   ln -s "/System/Library/CoreServices/Applications/Network Utility.app" "/Applications/Utilities/Network Utility.app"
fi

if [[ -L "/Applications/Utilities/Network Utility.app" ]]; then
   rm "/Applications/Utilities/Network Utility.app"
   ln -s "/System/Library/CoreServices/Applications/Network Utility.app" "/Applications/Utilities/Network Utility.app"
fi


#make a symbolic link from /System/Library/CoreServices/Applications/Wireless Diagnostics.app 
#to /Applications/Utilities so that Wireless Diagnostics.app is easier to access.

if [[ ! -e "/Applications/Utilities/Screen Sharing.app" ]]; then
   ln -s "/System/Library/CoreServices/Applications/Wireless Diagnostics.app" "/Applications/Utilities/Screen Sharing.app"
fi

if [[ -L "/Applications/Utilities/Screen Sharing.app" ]]; then
   rm "/Applications/Utilities/Screen Sharing.app"
   ln -s "/System/Library/CoreServices/Applications/Wireless Diagnostics.app" "/Applications/Utilities/Screen Sharing.app"
fi


#set power settings for loaners, 180 mins for sleep, 60 mins for display sleep
pmset sleep 180 disksleep 0 displaysleep 60 halfdim 1

#hide amagent account
dscl . create /Users/amagent IsHidden 1
mv /Users/amagent /var/amagent
dscl . -create /Users/amagent NFSHomeDirectory /var/amagent

#turn SSH on for adminlocal only
systemsetup -setremotelogin on
dseditgroup -o create -a adminlocal -t user -u adminlocal -q com.apple.access_ssh


#turn off Gatekeeper
spctl --master-disable


#disable annoying pop-ups on first use
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion 10.10.4


# Configure Finder to use Column View
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.finder "AlwaysOpenWindowsInColumnView" -bool true


#Enable Reduce Transparency for performance boost in Yosemite
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.universalaccess.plist  reduceTransparency 1  


#Remove setup LaunchDaemon
srm /Library/LaunchDaemons/com.ocadu.loanerinitialsetup.plist


#Self-Destruct
srm $0
