#!/bin/sh

###
# First Boot Script for ACS-Managed computers
###


#Set time zone
/usr/sbin/systemsetup -settimezone America/Toronto
/usr/sbin/systemsetup -setusingnetworktime on
/usr/sbin/systemsetup -gettime
/usr/sbin/systemsetup -gettimezone

#Let it catch up
sleep 5

#Make FireWire networking inactive
/usr/sbin/networksetup -setnetworkserviceenabled FireWire off


#Turning Airport off and make sure service is enabled
#This is useful for ACS-Managed computers that must be on ethernet at all times
networksetup -setairportpower Wi-Fi off; networksetup -setairportpower Wi-Fi off
networksetup -setnetworkserviceenabled Wi-Fi off


#Disable "Remember this network" for Airport
/usr/libexec/airportd prefs RememberRecentNetworks=NO


#Setting power to sleep at 2 hours, sleep the display at 30 minutes, half dim at 15 mins of inactivity
pmset sleep 120 disksleep 1 displaysleep 30 halfdim 15


#Disabling Blueooth from nagging if keyboard/mouse are not found
defaults write /Library/Preferences/com.apple.Bluetooth.plist BluetoothAutoSeekKeyboard 0
defaults write /Library/Preferences/com.apple.Bluetooth.plist BluetoothAutoSeekPointingDevice 0


#Turn SSH on
systemsetup -setremotelogin on
# wipe the disabled launchd key in the ssh.plist on the target to allow launchctl to load it
/usr/libexec/PlistBuddy -c "Delete Disabled" "/System/Library/LaunchDaemons/ssh.plist"
#make the ssh group
dscl . create /Groups/com.apple.access_ssh || exit 1
dscl . create /Groups/com.apple.access_ssh realname "Remote Login ACL"
dscl . create /Groups/com.apple.access_ssh gid 404
#add our user to the ssh group
dscl . -merge /Groups/com.apple.access_ssh GroupMembership adminlocal
launchctl load /System/Library/LaunchDaemons/ssh.plist

#Configure Finder to use Column View
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.finder "AlwaysOpenWindowsInColumnView" -bool true

#Disable annoying first time setup prompts from OS X
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool true
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion 10.10.0

#Enable solid scrollbars
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/.GlobalPreferences AppleShowScrollBars -string Always

#Turn off Gatekeeper
spctl --master-disable 
  
  
#Enable Reduce Transparency for performance boost in Yosemite
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.universalaccess.plist  reduceTransparency 1  

#Hide amagent account
dscl . create /Users/amagent IsHidden 1
mv /Users/amagent /var/amagent
dscl . -create /Users/amagent NFSHomeDirectory /var/amagent


##Kickstart ARD
KICKSTRT="/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart"
$KICKSTRT -configure -allowAccessFor -specifiedUsers
sleep 1
$KICKSTRT -activate -configure -users adminlocal -privs -all -access -on -restart -agent


#Set the login window to name and password
defaults write /Library/Preferences/com.apple.loginwindow SHOWFULLNAME -bool true


#Turn off DS_Store file creation on network volumes
defaults write /System/Library/User\ Template/English.lproj/Library/Preferences/com.apple.desktopservices DSDontWriteNetworkStores true


###AM Section###

#This will assist configuring AM agents beyond the very basic configuration included with the agent

#Enable remote
#defaults write /Library/Preferences/com.poleposition-sw.lanrev_agent.plist AbsoluteRemoteEnabled true

#Specify password for remote
#defaults write /Library/Preferences/com.poleposition-sw.lanrev_agent.plist AbsoluteRemotePassword 686D64AACB64A3CC8775639F308742BBB3C479B42CCFA14B

#Specify port for remote
#defaults write /Library/Preferences/com.poleposition-sw.lanrev_agent.plist AbsoluteRemotePort 5901

#No user confirmation required for remote
#defaults write /Library/Preferences/com.poleposition-sw.lanrev_agent.plist AbsoluteRemoteUserConfirmationRequired false

#Check for Apple Software Updates
#defaults write /Library/Preferences/com.poleposition-sw.lanrev_agent.plist CheckAppleSoftwarePatches true

#Check for Third-party patches
#defaults write /Library/Preferences/com.poleposition-sw.lanrev_agent.plist CheckThirdPartySoftwarePatches true

#Send heartbeat
#/Library/Application\ Support/LANrev\ Agent/LANrev\ Agent.app/Contents/MacOS/LANrev\ Agent --SendHeartbeat

#Send inventory
#/Library/Application\ Support/LANrev\ Agent/LANrev\ Agent.app/Contents/MacOS/LANrev\ Agent --SendInventory

#Check for packages
#/Library/Application\ Support/LANrev\ Agent/LANrev\ Agent.app/Contents/MacOS/LANrev\ Agent --SDCheck

#and because Mavericks/Yosemite are jerks
sudo killall cfprefsd

exit 0
